# Site settings
title: wadackel.me
description: wadackel.meは、わだ つよし(@wadackel)の技術xプライベートなブログです。ダックスフンド is かわいい。
author:
  jp: 和田 剛
  en: tsuyoshi wada
  description: ダックスフンド is かわいい。
baseurl: ""
url: http://blog.wadackel.me
permalink: /:year/:title/

# Social
twitter_username: wadackel
github_username:  tsuyoshiwada

# Paginator
paginate: 20
paginate_path: /page/:num

# Build settings
include: [assets, _pages]
exclude: [vendor, Gemfile, Gemfile.lock, node_modules, src, gulpfile.js, package.json, npm-debug.log]
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-paginate
  - jekyll-auto-image

defaults:
  -
    scope:
      path:   ""
      type:   "pages"
    values:
      layout: "page"
  -
    scope:
      path:   ""
      type:   "posts"
    values:
      layout: "post"

# Images
image: /assets/images/wadackelme.png
