baseurl: "http://blog.wadackel.me/"
title: "wadackel.me"
description: "wadackel.meは、わだ つよし(@wadackel)の技術xプライベートなブログです。ダックスフンド is かわいい。"
languageCode: "ja"
author:
  jp: "和田 剛"
  en: "tsuyoshi wada"
  description: "ダックスフンド is かわいい。"
permalinks:
  post: /:year/:title/


# Social
twitter_username: "wadackel"
github_username:  "tsuyoshiwada"
