---
title: "wadackel.me"
baseurl: "https://blog.wadackel.me/"
defaultContentLanguage: "ja"
permalinks:
  post: /:year/:slug/
googleAnalytics: "UA-76551157-1"
paginate: 20
paginatePath: "page"
metaDataFormat: "yaml"
hasCJKLanguage: true

markup:
  goldmark:
    renderer:
      unsafe: true

blackfriday:
  extensions:
  - backslashLineBreak

# More options
params:
  # Basic
  description: "wadackel.meは、わだ つよし(@wadackel)の技術xプライベートなブログです。ダックスフンド is かわいい。"
  image: "/images/wadackelme.png"
  author:
    jp: "和田 剛"
    en: "tsuyoshi wada"
    description: "ダックスフンド is かわいい。"

  # Social
  twitter: "wadackel"
  github:  "wadackel"
