---
title: "wadackel.me"
baseurl: "http://blog.wadackel.me/"
permalinks:
  post: /:year/:filename/
canonifyurls: true
googleAnalytics: ""
paginate: 20
paginatePath: "page"
metaDataFormat: "yaml"
hasCJKLanguage: true

# Markdown
blackfriday:
  extensions:
    - autoHeaderIds
    - autoLinking
    - fencedCodeBlocks
    - definitionLists
    - strikethrough

# More options
params:
  # Basic
  description: "wadackel.meは、わだ つよし(@wadackel)の技術xプライベートなブログです。ダックスフンド is かわいい。"
  author:
    jp: "和田 剛"
    en: "tsuyoshi wada"
    description: "ダックスフンド is かわいい。"

  # Social
  twitter: "wadackel"
  github:  "tsuyoshiwada"
