---
title: "wadackel.me"
baseurl: "https://blog.wadackel.me/"
permalinks:
  post: /:year/:slug/
canonifyurls: true
googleAnalytics: "UA-76551157-1"
paginate: 20
paginatePath: "page"
metaDataFormat: "yaml"
hasCJKLanguage: true

# Markdown
blackfriday:
  plainIDAnchors: true
  extensions:
    - autoLinking
    - fencedCodeBlocks
    - definitionLists
    - strikethrough
  extensionsmask:
    - autoHeaderIds

# More options
params:
  # Basic
  description: "wadackel.meは、わだ つよし(@wadackel)の技術xプライベートなブログです。ダックスフンド is かわいい。"
  image: "/images/wadackelme.png"
  author:
    jp: "和田 剛"
    en: "tsuyoshi wada"
    description: "ダックスフンド is かわいい。"

  # Social
  twitter: "wadackel"
  github:  "tsuyoshiwada"
