version: 2

references:
  yarn_cache_config: &yarn_cache_config
    key: dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
    paths:
      - .

  yarn_restore_cache: &yarn_restore_cache
    restore_cache:
      <<: *yarn_cache_config
      name: Restore yarn cache

  yarn_save_cache: &yarn_save_cache
    save_cache:
      <<: *yarn_cache_config
      name: Save yarn cache

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - *yarn_restore_cache
      - run:
          name: Install dependencies
          command: yarn --pure-lock
      - *yarn_save_cache
      - run:
          name: Check code format
          command: |
            yarn lint
            yarn format && git diff --exit-code || exit 1
